name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - foxy
          - galactic
          - humble
          - rolling
        include:
          # Foxy Fitzroy
          - os: ubuntu
            os_release: focal
            ros_distribution: foxy
            ros_version: 2
          # Galactic Geochelone
          - os: ubuntu
            os_release: focal
            ros_distribution: galactic
            ros_version: 2
          # Humble Hawksbill
          - os: ubuntu
            os_release: jammy
            ros_distribution: humble
            ros_version: 2
          # Rolling Ridley
          - os: ubuntu
            os_release: focal
            ros_distribution: rolling
            ros_version: 2
    container:
      image: '${{ matrix.os }}:${{ matrix.os_release }}'
    steps:
      - name: install prereqs
        run: apt update && apt install -y sudo curl software-properties-common
      - name: install eCAL
        run: |
          add-apt-repository ppa:ecal/ecal-latest \
          ; apt-get update \
          ; apt-get install -y ecal \
      - name: setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src
      - name: setup ROS environment
        uses: ros-tooling/setup-ros@v0.3
        with:
          use-ros2-testing: false
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: rosdep install
        run: "rosdep update && rosdep install -r --from-paths ros_ws/src --ignore-src --rosdistro ${{ matrix.ros_distribution }} -y"
      - name: build
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: rmw_ecal_dynamic_cpp
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
